eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
      defaultZone: http://localhost:8888/eureka
      instance:
       hostname: localhost
       name: eureka-service
       
spring:
  jackson:
    serialization:
        FAIL_ON_EMPTY_BEANS : false       
