spring:
   application:
    name: project-service

server:
  port: 8308


eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
      defaultZone: http://localhost:8888/eureka/
      instance:
       hostname: localhost
       name: eureka-service